### PR TITLE
Add hint about end line issues in git repositories

### PR DESCRIPTION
**Pull request by rafaeljusto**
See #47

### CODE REVIEW

**Comment by sjkaliski** [comment]
@rafaeljusto looks like there is a test failure in [build](https://travis-ci.org/beme/abide/jobs/462728065) related to Go 1.8.x.

We just merged in another PR (https://github.com/beme/abide/pull/50) which removes support for Go 1.8.x. If you rebase, should be ok!

**Comment by rafaeljusto** [comment]
Cool, thanks! All checks have passed now. 😄

**Comment by amir20** [comment]
Is there plan to merge this?

**Comment by rafaeljusto** [comment]
@amir20 Only @sjkaliski can merge this PR 😄

**Comment by sjkaliski** [comment]
@rafaeljusto thanks! and sorry for the delay 😞

**Comment by rafaeljusto** [comment]
No probs 😄 👍

**Pull request merged**
